[package]
name = "percent"
description = "A CLI tool for Percent Encoding and Decoding"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
clap_complete = "4.5.6"
urlencoding = "2.1.3"
